#!/usr/bin/env bash
set -euo pipefail

# Speakeasy Lite installer.
# - Builds the venv via scripts/setup.sh
# - Installs a desktop entry in the KDE/GNOME application menu
# - Installs an XDG autostart entry so it runs on login
# - Generates an uninstall.sh that reverses everything above

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_NAME="speakeasy-lite"
APP_TITLE="Speakeasy Lite"
DESKTOP_NAME="${APP_NAME}.desktop"

APP_MENU_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/applications"
AUTOSTART_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/autostart"
APP_DESKTOP="${APP_MENU_DIR}/${DESKTOP_NAME}"
AUTOSTART_DESKTOP="${AUTOSTART_DIR}/${DESKTOP_NAME}"

VENV_PY="${PROJECT_DIR}/.venv/bin/python"
APP_PY="${PROJECT_DIR}/app/main.py"
EXEC_LINE="${VENV_PY} ${APP_PY}"

# Stop any currently running instance so the post-install code takes over.
if pgrep -f "${APP_PY}" >/dev/null 2>&1; then
    echo "==> Stopping running Speakeasy Lite..."
    pkill -f "${APP_PY}" || true
    sleep 1
fi

echo "==> Building venv and installing Python dependencies..."
bash "${PROJECT_DIR}/scripts/setup.sh"

echo "==> Installing application menu entry..."
mkdir -p "${APP_MENU_DIR}"
cat > "${APP_DESKTOP}" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=${APP_TITLE}
Comment=Local dictation utility (push-to-talk, GPU Whisper)
Exec=${EXEC_LINE}
Icon=audio-input-microphone
Categories=Utility;AudioVideo;
Terminal=false
StartupNotify=false
EOF
echo "    -> ${APP_DESKTOP}"

echo "==> Installing XDG autostart entry..."
mkdir -p "${AUTOSTART_DIR}"
cat > "${AUTOSTART_DESKTOP}" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=${APP_TITLE}
Comment=Local dictation utility (autostart at login)
Exec=${EXEC_LINE}
Icon=audio-input-microphone
Terminal=false
StartupNotify=false
X-GNOME-Autostart-enabled=true
Hidden=false
EOF
echo "    -> ${AUTOSTART_DESKTOP}"

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "${APP_MENU_DIR}" 2>/dev/null || true
fi

echo "==> Generating uninstall.sh..."
cat > "${PROJECT_DIR}/uninstall.sh" <<EOF
#!/usr/bin/env bash
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Reverses what install.sh did: kills the running app, removes the menu entry
# and the autostart entry. Leaves the venv, models, prefs, and log in place --
# delete the project directory to fully remove.

set -euo pipefail

APP_DESKTOP="${APP_DESKTOP}"
AUTOSTART_DESKTOP="${AUTOSTART_DESKTOP}"
APP_MENU_DIR="${APP_MENU_DIR}"
APP_PY="${APP_PY}"
PROJECT_DIR="${PROJECT_DIR}"

if pgrep -f "\${APP_PY}" >/dev/null 2>&1; then
    echo "==> Stopping running Speakeasy Lite..."
    pkill -f "\${APP_PY}" || true
fi

echo "==> Removing menu entry..."
rm -f "\${APP_DESKTOP}"
echo "    -> \${APP_DESKTOP}"

echo "==> Removing autostart entry..."
rm -f "\${AUTOSTART_DESKTOP}"
echo "    -> \${AUTOSTART_DESKTOP}"

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "\${APP_MENU_DIR}" 2>/dev/null || true
fi

cat <<MSG

Uninstall complete.

The following are preserved on disk -- delete the project directory
(\${PROJECT_DIR}) to fully remove:

  .venv/         (Python environment with CUDA wheels, ~3 GB)
  models/        (Whisper model cache, ~1.5 GB)
  prefs.json     (floating button position + enabled state)
  speakeasy.log  (log file)
MSG
EOF
chmod +x "${PROJECT_DIR}/uninstall.sh"
echo "    -> ${PROJECT_DIR}/uninstall.sh"

cat <<EOF

Install complete.

Speakeasy Lite is now:
  - In your application menu (search for "Speakeasy")
  - Set to launch automatically on next login

To launch right now without logging out:
  ${EXEC_LINE} &

To uninstall later:
  bash ${PROJECT_DIR}/uninstall.sh
EOF
